- name: OpenWhisk LoadBalancer
  hosts: main
  tasks:
  - name: (Re)start container
    docker:
      name: loadbalancer
      image: whisk/loadbalancer
      state: reloaded
      restart_policy: "{{docker.restart.policy}}"
      env:
        "CONSULSERVER_HOST": "{{consul.host}}"
        "CONSUL_HOST_PORT4": "{{consul.port4}}"
        "PORT": 8080
        "KAFKA_NUMPARTITIONS": 2
      volumes:
        - "{{whisk.logs.dir}}/loadBalancer:/logs"
      ports:
        - "{{loadBalancer.port}}:8080"